version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    command: npm start
    volumes:
      - ./server/:/src
      - /src/node_modules
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - ATLAS_URI
      - PORT
    networks:
      - backend
      - frontend

  mongo:
    image: mongo
    volumes:
      - data-volume:/db
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    networks:
      - backend

  client:
    build:
      context: ./client
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    depends_on:
      - server
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - frontend 

networks:
  backend:
  frontend:

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
